### ISSUE TITLE
run-generator throws an intermittent "Invalid argument" on Windows

### ISSUE THREAD

**Issue by Rufflewind** [Rufflewind/calico#2]
This has happened at least twice during the monthly Windows builds, but I can't ever reproduce it after a retry.

Most recent failure: https://github.com/Rufflewind/calico/actions/runs/1199319438

> build (windows-latest)
> failed on 2021-09-03T20:26:22Z in 38s

```
Run make
  make
  shell: C:\msys64\usr\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
cp src/arithmetic.h include/calico/arithmetic.h
tools/run-generator >src/arithmetic_impl_g.h.tmp src/arithmetic_impl_g.h.gen.py
mv src/arithmetic_impl_g.h.tmp src/arithmetic_impl_g.h
cp src/arithmetic_impl_g.h include/calico/arithmetic_impl_g.h
cp src/binary_search.h include/calico/binary_search.h
cp src/btree.hpp include/calico/btree.hpp
cp src/btree_head.h include/calico/btree_head.h
cp src/btree_impl.h include/calico/btree_impl.h
cp src/btree_template.h include/calico/btree_template.h
tools/run-generator >src/btree_impl_ids.txt.tmp src/btree_impl_ids.txt.gen.py
Traceback (most recent call last):
  File "D:\a\calico\calico\tools\run-generator", line 8, in <module>
    utils.FileGenerator(fn).main()
  File "D:\a\calico\calico\src\btree_impl_ids.txt.gen.py", line 6, in main
    utils.pexec(["parse-global-identifiers"] + __deps__)
  File "D:\a\calico\calico\tools\utils.py", line 37, in pexec
    os.execvp(args[0], args)
  File "C:\msys64\mingw64\lib\python3.9\os.py", line 574, in execvp
    _execvpe(file, args)
  File "C:\msys64\mingw64\lib\python3.9\os.py", line 615, in _execvpe
    raise saved_exc
  File "C:\msys64\mingw64\lib\python3.9\os.py", line 607, in _execvpe
    exec_func(fullname, *argrest)
OSError: [Errno 22] Invalid argument
make: *** [Makefile:202: src/btree_impl_ids.txt] Error 1
Error: Process completed with exit code 2.
```

**Comment by Rufflewind** [comment]
https://github.com/Rufflewind/calico/files/7110336/logs_14.zip

**Comment by Rufflewind** [comment]
Turns out the command `tools/run-generator >src/btree_impl_ids.txt.tmp src/btree_impl_ids.txt.gen.py` has never worked on Windows, but this command is rarely exercised in the Windows builds. This command is part of a Makefile rule:

```
src/btree_impl_ids.txt: src/btree_impl.h src/btree_impl_ids.txt.gen.py
	tools/run-generator >$@.tmp src/btree_impl_ids.txt.gen.py
	mv $@.tmp $@
```

*The output file `src/btree_impl_ids.txt` is checked into Git,* which means whether this rule will fire depends entirely on how the files get unpacked into the Git workspace, which is nondeterministic. Most of the time, if it happens fast enough, the [files will have the same timestamp](https://github.com/Rufflewind/calico/runs/3514902833) and the rule will be skipped:

```
$ ls -alht --time-style=full-iso src/* || :
...
-rw-r--r-- 1 runneradmin None  38K 2021-09-04 21:03:04.789739500 +0000 src/btree_impl.h
-rw-r--r-- 1 runneradmin None  793 2021-09-04 21:03:04.789739500 +0000 src/btree_impl_ids.txt
-rw-r--r-- 1 runneradmin None  118 2021-09-04 21:03:04.789739500 +0000 src/btree_impl_ids.txt.gen.py
```

However, occasionally the job might be running a little slower or we might get unlucky, in which case the [timestamps could differ](https://github.com/Rufflewind/calico/runs/3514871203):

```
$ ls -alht --time-style=full-iso src/* || :
...
-rw-r--r-- 1 runneradmin None  118 2021-09-04 20:52:22.636533000 +0000 src/btree_impl_ids.txt.gen.py
...
-rw-r--r-- 1 runneradmin None  38K 2021-09-04 20:52:22.635533000 +0000 src/btree_impl.h
-rw-r--r-- 1 runneradmin None  793 2021-09-04 20:52:22.635533000 +0000 src/btree_impl_ids.txt
```
